### ISSUE TITLE
Header generation

### ISSUE THREAD

**Issue by encima** [marcusolsson/json-schema-docs#1]
Thank you for creating such an easy to use lib for this without the need for 3000 node modules!

Right now, the generator creates headings beyond the H6 supported by Markdown so it is rendered as plain text with hashes prefixed

Possible solutions:
- Switch to HTML after h6 to support up to h8
- Add a config option of what to do when the headers go beyond this (i.e. embolden text)

<img width="595" alt="image" src="https://user-images.githubusercontent.com/517923/86230164-02cf1800-bb91-11ea-92b2-5a25121b1910.png">

**Comment by marcusolsson** [comment]
Sorry about the _very_ late response on this (didn't see this until know). 

I'd like to avoid adding HTML since it prevent using the tool where HTML isn't allowed. I think making the text bold is a reasonable fix for this.
