### ISSUE TITLE
[Question]How to set multi-value for  template query variables.

### ISSUE THREAD

**Issue by jqhr** [marcusolsson/json-schema-docs#3]
I have a problem--automatic repeat panel in a dashboard. The datasource is jsonapi, but the api return an array.So I must to use template query variable and enable multi-value. I enabled it, but it transfer array to JSON string.
How to solve it?

**Comment by marcusolsson** [comment]
I think you posted this in the wrong repository. Closing.

**Comment by jqhr** [comment]
Oh, sorry
